//color

export const COLOR_CHAT = [
  "#006AD4",
  "#02B28D",
  "#4C9CF2",
  "#5B5B5B",
  "#68D400",
  "#692CF2",
  "#77A2F2",
  "#AB41D4",
  "#B51299",
  "#B76618",
  "#EDA600",
  "#EE046B",
  "#FF311E",
];

//color

//
export const OPEN_MODAL_REGISTER = "OPEN_MODAL_REGISTER";
//
export const CLOSE_MODAL = "CLOSE_MODAL";
//
export const REGISTER_ACCOUNT = "REGISTER_ACCOUNT";
//
export const ON_LOADING_SUBMIT_MODAL = "ON_LOADING_SUBMIT_MODAL";
//
export const OFF_LOADING_SUBMIT_MODAL = "OFF_LOADING_SUBMIT_MODAL";
//
export const LOGIN = "LOGIN";
//
export const LOGOUT = "LOGOUT";
//
export const OPEN_MODAL_PROFILE = "OPEN_MODAL_PROFILE";
//
export const OPEN_MODAL_ADD_FRIEND = "OPEN_MODAL_ADD_FRIEND";
//
export const OPEN_MODAL_CREATE_GROUP = "OPEN_MODAL_CREATE_GROUP";
//
export const SEARCH_USER_BY_EMAIL_OR_PHONE = "SEARCH_USER_BY_EMAIL_OR_PHONE";
//
export const LOAD_INFORMATION_PROFILE = "LOAD_INFORMATION_PROFILE";
//
export const STATUS_FRIEND = "STATUS_FRIEND";
//
export const GET_ALL_INVITE_REQUEST = "GET_ALL_INVITE_REQUEST";
//
export const LOAD_CONTENT_LIST_CONNECT_FRIEND =
  "LOAD_CONTENT_LIST_CONNECT_FRIEND";
//
export const LOAD_CONTENT_LIST_GROUP = "LOAD_CONTENT_LIST_GROUP";
//
export const LOAD_CONTENT_LIST_INVITE_FRIEND =
  "LOAD_CONTENT_LIST_INVITE_FRIEND";
//
export const CHANGE_LOADING_TO_CONTENT = "CHANGE_LOADING_TO_CONTENT";
//
export const CHANGE_CONTENT_TO_LOADING = "CHANGE_CONTENT_TO_LOADING";
//
export const LOAD_LIST_FRIEND = "LOAD_LIST_FRIEND";
//
export const ADD_MESSAGE = "ADD_MESSAGE";
//
export const ADD_GROUP_MESSAGE = "ADD_GROUP_MESSAGE";
//
export const LOAD_ALL_MESSAGE_OF_USER_BY_ID = "LOAD_ALL_MESSAGE_OF_USER_BY_ID";
//
export const GET_ALL_MESSAGE_CONTENT_RIGHT = "GET_ALL_MESSAGE_CONTENT_RIGHT";
//
export const GET_ALL_MESSAGES_BY_GROUP = "GET_ALL_MESSAGES_BY_GROUP";
//
export const OPEN_MODAL_CHANGE_NICK_NAME = "OPEN_MODAL_CHANGE_NICK_NAME";
//
export const OPEN_MODAL_CHANGE_COLOR_CHAT = "OPEN_MODAL_CHANGE_COLOR_CHAT";
//
export const OPEN_MODAL_CHANGE_ICON_CHAT = "OPEN_MODAL_CHANGE_ICON_CHAT";
//
export const OPEN_MODAL_WARNING_LEAVE_GROUP = "OPEN_MODAL_WARNING_LEAVE_GROUP";
//
export const OPEN_MODAL_MEMBER_GROUP_CHAT = "OPEN_MODAL_MEMBER_GROUP_CHAT";
//
export const UPDATE_COLOR_CHAT = "UPDATE_COLOR_CHAT";
//
export const UPDATE_NAME_GROUP_MESSAGE = "UPDATE_NAME_GROUP_MESSAGE";
//
export const OPEN_MODAL_CHANGE_NAME_GROUP = "OPEN_MODAL_CHANGE_NAME_GROUP";
//
export const UPDATE_NICK_NAME_USER = "UPDATE_NICK_NAME_USER";
//
export const UPDATE_ICON_CHAT_MESSAGE = "UPDATE_ICON_CHAT_MESSAGE";
//
export const OPEN_MODAL_WARNING_MESSGAE = "OPEN_MODAL_WARNING_MESSGAE";
//
export const DELETE_MESSAGE_REQUEST = "DELETE_MESSAGE_REQUEST";
//
export const GET_ALL_USERS = "GET_ALL_USERS";
//
export const OPEN_MODAL_FEEL_MESSAGE = "OPEN_MODAL_FEEL_MESSAGE";
//
export const UPDATE_IMAGE_GROUP_MESSAGE = "UPDATE_IMAGE_GROUP_MESSAGE";
//
export const LOAD_SOCKET = "LOAD_SOCKET";
//
export const SET_TYPING_MESSAGE = "SET_TYPING_MESSAGE";
//
export const OPEN_MODAL_CALL = "OPEN_MODAL_CALL";
//
export const OPEN_MODAL_LOADING_UPLOAD_IMAGE_GROUP =
  "OPEN_MODAL_LOADING_UPLOAD_IMAGE_GROUP";
//
