//
export const OPEN_MODAL_REGISTER = "OPEN_MODAL_REGISTER";
//
export const CLOSE_MODAL = "CLOSE_MODAL";
//
export const REGISTER_ACCOUNT = "REGISTER_ACCOUNT";
//
export const ON_LOADING_SUBMIT_MODAL = "ON_LOADING_SUBMIT_MODAL";
//
export const OFF_LOADING_SUBMIT_MODAL = "OFF_LOADING_SUBMIT_MODAL";
//
export const LOGIN = "LOGIN";
//
export const LOGOUT = "LOGOUT";
//
export const OPEN_MODAL_PROFILE = "OPEN_MODAL_PROFILE";
//
export const OPEN_MODAL_ADD_FRIEND = "OPEN_MODAL_ADD_FRIEND";
//
export const OPEN_MODAL_CREATE_GROUP = "OPEN_MODAL_CREATE_GROUP";
//
